import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiLeetcode,
  SiSqlite,
  SiExpress,
  SiSpringboot,
  SiNestjs,
  SiJest,
  SiPrometheus,
  SiApacheairflow,
  SiKubernetes,
  SiGrafana,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaNodeJs,
} from "react-icons/fa6";
import { CgCPlusPlus } from "react-icons/cg";
import {
  DiAws,
  DiDjango,
  DiDocker,
  DiGoogleCloudPlatform,
  DiJava,
  DiMongodb,
  DiPostgresql,
  DiPython,
  DiRedis,
} from "react-icons/di";
import { GrGraphQl, GrKubernetes, GrReactjs } from "react-icons/gr";
import { TbBrandReactNative } from "react-icons/tb";
import { MdQueue } from "react-icons/md";

export const iconLibrary: Record<string, IconType> = {
  cpp: CgCPlusPlus,
  java: DiJava,
  python: DiPython,
  sql: SiSqlite,
  nodejs: FaNodeJs,
  expressjs: SiExpress,
  django: DiDjango,
  springboot: SiSpringboot,
  nestjs: SiNestjs,
  reactjs: GrReactjs,
  reactnative: TbBrandReactNative,
  jest: SiJest,
  kubernetes: SiKubernetes,
  grafana:SiGrafana,
  docker: DiDocker,
  kafka: MdQueue,
  prometheus: SiPrometheus,
  prefect: SiApacheairflow,
  git: FaGithub,
  graphql: GrGraphQl,
  mongodb: DiMongodb,
  postgresql: DiPostgresql,
  redis: DiRedis,
  aws:DiAws,
  gcp:DiGoogleCloudPlatform,
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  leetcode: SiLeetcode,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
